version: '3.7'

services:
  grpc_server:
    build: ./
    network_mode: bridge
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      GRPC_SERVER_HOST: 127.0.0.1
      GRPC_SERVER_PORT: 6001
      GRPC_SERVER_PROTOCOL: https
      CERTIFICATE_PATH: SSL/local1-server.crt
