# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airlines.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='airlines.proto',
  package='nycflights',
  syntax='proto3',
  serialized_options=b'\252\002\014GrpcAirlines',
  serialized_pb=b'\n\x0e\x61irlines.proto\x12\nnycflights\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x0f\x41irlineResponse\x12%\n\x08\x61irlines\x18\x01 \x03(\x0b\x32\x13.nycflights.Airline\"(\n\x07\x41irline\x12\x0f\n\x07\x63\x61rrier\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2N\n\x08\x41irlines\x12\x42\n\x0bGetAirlines\x12\x16.google.protobuf.Empty\x1a\x1b.nycflights.AirlineResponseB\x0f\xaa\x02\x0cGrpcAirlinesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AIRLINERESPONSE = _descriptor.Descriptor(
  name='AirlineResponse',
  full_name='nycflights.AirlineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='airlines', full_name='nycflights.AirlineResponse.airlines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=115,
)


_AIRLINE = _descriptor.Descriptor(
  name='Airline',
  full_name='nycflights.Airline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carrier', full_name='nycflights.Airline.carrier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='nycflights.Airline.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=157,
)

_AIRLINERESPONSE.fields_by_name['airlines'].message_type = _AIRLINE
DESCRIPTOR.message_types_by_name['AirlineResponse'] = _AIRLINERESPONSE
DESCRIPTOR.message_types_by_name['Airline'] = _AIRLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AirlineResponse = _reflection.GeneratedProtocolMessageType('AirlineResponse', (_message.Message,), {
  'DESCRIPTOR' : _AIRLINERESPONSE,
  '__module__' : 'airlines_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.AirlineResponse)
  })
_sym_db.RegisterMessage(AirlineResponse)

Airline = _reflection.GeneratedProtocolMessageType('Airline', (_message.Message,), {
  'DESCRIPTOR' : _AIRLINE,
  '__module__' : 'airlines_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Airline)
  })
_sym_db.RegisterMessage(Airline)


DESCRIPTOR._options = None

_AIRLINES = _descriptor.ServiceDescriptor(
  name='Airlines',
  full_name='nycflights.Airlines',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=159,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAirlines',
    full_name='nycflights.Airlines.GetAirlines',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AIRLINERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRLINES)

DESCRIPTOR.services_by_name['Airlines'] = _AIRLINES

# @@protoc_insertion_point(module_scope)
