# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Protos.airlines_pb2 as airlines__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AirlinesStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAirlines = channel.unary_unary(
                '/nycflights.Airlines/GetAirlines',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=airlines__pb2.AirlineResponse.FromString,
                )


class AirlinesServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetAirlines(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirlinesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAirlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirlines,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=airlines__pb2.AirlineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nycflights.Airlines', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Airlines(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetAirlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Airlines/GetAirlines',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            airlines__pb2.AirlineResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
