# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airports.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='airports.proto',
  package='nycflights',
  syntax='proto3',
  serialized_options=b'\252\002\013GrpcWeather',
  serialized_pb=b'\n\x0e\x61irports.proto\x12\nnycflights\x1a\x1bgoogle/protobuf/empty.proto\"7\n\x0f\x41irportResponse\x12$\n\x07\x61irport\x18\x01 \x03(\x0b\x32\x13.nycflights.Airport\"s\n\x07\x41irport\x12\x0b\n\x03\x66\x61\x61\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0b\n\x03lon\x18\x04 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x05 \x01(\x05\x12\n\n\x02tz\x18\x06 \x01(\x05\x12\x0b\n\x03\x64st\x18\x07 \x01(\t\x12\r\n\x05tzone\x18\x08 \x01(\t2N\n\x08\x41irports\x12\x42\n\x0bGetAirports\x12\x16.google.protobuf.Empty\x1a\x1b.nycflights.AirportResponseB\x0e\xaa\x02\x0bGrpcWeatherb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AIRPORTRESPONSE = _descriptor.Descriptor(
  name='AirportResponse',
  full_name='nycflights.AirportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='airport', full_name='nycflights.AirportResponse.airport', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=114,
)


_AIRPORT = _descriptor.Descriptor(
  name='Airport',
  full_name='nycflights.Airport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faa', full_name='nycflights.Airport.faa', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='nycflights.Airport.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='nycflights.Airport.lat', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lon', full_name='nycflights.Airport.lon', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='nycflights.Airport.alt', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tz', full_name='nycflights.Airport.tz', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst', full_name='nycflights.Airport.dst', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tzone', full_name='nycflights.Airport.tzone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=231,
)

_AIRPORTRESPONSE.fields_by_name['airport'].message_type = _AIRPORT
DESCRIPTOR.message_types_by_name['AirportResponse'] = _AIRPORTRESPONSE
DESCRIPTOR.message_types_by_name['Airport'] = _AIRPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AirportResponse = _reflection.GeneratedProtocolMessageType('AirportResponse', (_message.Message,), {
  'DESCRIPTOR' : _AIRPORTRESPONSE,
  '__module__' : 'airports_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.AirportResponse)
  })
_sym_db.RegisterMessage(AirportResponse)

Airport = _reflection.GeneratedProtocolMessageType('Airport', (_message.Message,), {
  'DESCRIPTOR' : _AIRPORT,
  '__module__' : 'airports_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Airport)
  })
_sym_db.RegisterMessage(Airport)


DESCRIPTOR._options = None

_AIRPORTS = _descriptor.ServiceDescriptor(
  name='Airports',
  full_name='nycflights.Airports',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=311,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAirports',
    full_name='nycflights.Airports.GetAirports',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AIRPORTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRPORTS)

DESCRIPTOR.services_by_name['Airports'] = _AIRPORTS

# @@protoc_insertion_point(module_scope)
