# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flights.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='flights.proto',
  package='nycflights',
  syntax='proto3',
  serialized_options=b'\252\002\013GrpcFlights',
  serialized_pb=b'\n\rflights.proto\x12\nnycflights\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x0e\x46lightResponse\x12\"\n\x06\x66light\x18\x01 \x03(\x0b\x32\x12.nycflights.Flight\"\x8e\x02\n\x06\x46light\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rrier\x18\x03 \x01(\t\x12\x0f\n\x07tailnum\x18\x04 \x01(\t\x12\x0e\n\x06\x66light\x18\x05 \x01(\x05\x12\x0c\n\x04year\x18\x06 \x01(\x05\x12\r\n\x05month\x18\x07 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x08 \x01(\x05\x12\x10\n\x08\x64\x65p_time\x18\t \x01(\x05\x12\x11\n\tdep_delay\x18\n \x01(\x05\x12\x10\n\x08\x61rr_time\x18\x0b \x01(\x05\x12\x11\n\tarr_delay\x18\x0c \x01(\x05\x12\x10\n\x08\x61ir_time\x18\r \x01(\x05\x12\x10\n\x08\x64istance\x18\x0e \x01(\x05\x12\x0c\n\x04hour\x18\x0f \x01(\x05\x12\x0e\n\x06minute\x18\x10 \x01(\x05\"\x1d\n\x0bMonthNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0c\x46lightsCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x9c\x01\n\x07\x46lights\x12@\n\nGetFlights\x12\x16.google.protobuf.Empty\x1a\x1a.nycflights.FlightResponse\x12O\n\x1aGetNumberOfFlightsPerMonth\x12\x17.nycflights.MonthNumber\x1a\x18.nycflights.FlightsCountB\x0e\xaa\x02\x0bGrpcFlightsb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_FLIGHTRESPONSE = _descriptor.Descriptor(
  name='FlightResponse',
  full_name='nycflights.FlightResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flight', full_name='nycflights.FlightResponse.flight', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=110,
)


_FLIGHT = _descriptor.Descriptor(
  name='Flight',
  full_name='nycflights.Flight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='nycflights.Flight.origin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='nycflights.Flight.dest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carrier', full_name='nycflights.Flight.carrier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tailnum', full_name='nycflights.Flight.tailnum', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flight', full_name='nycflights.Flight.flight', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='nycflights.Flight.year', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='nycflights.Flight.month', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='nycflights.Flight.day', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dep_time', full_name='nycflights.Flight.dep_time', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dep_delay', full_name='nycflights.Flight.dep_delay', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arr_time', full_name='nycflights.Flight.arr_time', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arr_delay', full_name='nycflights.Flight.arr_delay', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='air_time', full_name='nycflights.Flight.air_time', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='nycflights.Flight.distance', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hour', full_name='nycflights.Flight.hour', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minute', full_name='nycflights.Flight.minute', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=383,
)


_MONTHNUMBER = _descriptor.Descriptor(
  name='MonthNumber',
  full_name='nycflights.MonthNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='nycflights.MonthNumber.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=414,
)


_FLIGHTSCOUNT = _descriptor.Descriptor(
  name='FlightsCount',
  full_name='nycflights.FlightsCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='nycflights.FlightsCount.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=445,
)

_FLIGHTRESPONSE.fields_by_name['flight'].message_type = _FLIGHT
DESCRIPTOR.message_types_by_name['FlightResponse'] = _FLIGHTRESPONSE
DESCRIPTOR.message_types_by_name['Flight'] = _FLIGHT
DESCRIPTOR.message_types_by_name['MonthNumber'] = _MONTHNUMBER
DESCRIPTOR.message_types_by_name['FlightsCount'] = _FLIGHTSCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlightResponse = _reflection.GeneratedProtocolMessageType('FlightResponse', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTRESPONSE,
  '__module__' : 'flights_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.FlightResponse)
  })
_sym_db.RegisterMessage(FlightResponse)

Flight = _reflection.GeneratedProtocolMessageType('Flight', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHT,
  '__module__' : 'flights_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Flight)
  })
_sym_db.RegisterMessage(Flight)

MonthNumber = _reflection.GeneratedProtocolMessageType('MonthNumber', (_message.Message,), {
  'DESCRIPTOR' : _MONTHNUMBER,
  '__module__' : 'flights_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.MonthNumber)
  })
_sym_db.RegisterMessage(MonthNumber)

FlightsCount = _reflection.GeneratedProtocolMessageType('FlightsCount', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTSCOUNT,
  '__module__' : 'flights_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.FlightsCount)
  })
_sym_db.RegisterMessage(FlightsCount)


DESCRIPTOR._options = None

_FLIGHTS = _descriptor.ServiceDescriptor(
  name='Flights',
  full_name='nycflights.Flights',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=448,
  serialized_end=604,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFlights',
    full_name='nycflights.Flights.GetFlights',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FLIGHTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNumberOfFlightsPerMonth',
    full_name='nycflights.Flights.GetNumberOfFlightsPerMonth',
    index=1,
    containing_service=None,
    input_type=_MONTHNUMBER,
    output_type=_FLIGHTSCOUNT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLIGHTS)

DESCRIPTOR.services_by_name['Flights'] = _FLIGHTS

# @@protoc_insertion_point(module_scope)
