# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Protos.flights_pb2 as flights__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FlightsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlights = channel.unary_unary(
                '/nycflights.Flights/GetFlights',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=flights__pb2.FlightResponse.FromString,
                )
        self.GetNumberOfFlightsPerMonth = channel.unary_unary(
                '/nycflights.Flights/GetNumberOfFlightsPerMonth',
                request_serializer=flights__pb2.MonthNumber.SerializeToString,
                response_deserializer=flights__pb2.FlightsCount.FromString,
                )


class FlightsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetFlights(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfFlightsPerMonth(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlights,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=flights__pb2.FlightResponse.SerializeToString,
            ),
            'GetNumberOfFlightsPerMonth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfFlightsPerMonth,
                    request_deserializer=flights__pb2.MonthNumber.FromString,
                    response_serializer=flights__pb2.FlightsCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nycflights.Flights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Flights(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetFlights',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            flights__pb2.FlightResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNumberOfFlightsPerMonth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetNumberOfFlightsPerMonth',
            flights__pb2.MonthNumber.SerializeToString,
            flights__pb2.FlightsCount.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
