# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Protos import flights_pb2 as Protos_dot_flights__pb2
from Protos import weather_pb2 as Protos_dot_weather__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FlightsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlights = channel.unary_unary(
                '/nycflights.Flights/GetFlights',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.FlightResponse.FromString,
                )
        self.GetNumberOfFlightsPerMonth = channel.unary_unary(
                '/nycflights.Flights/GetNumberOfFlightsPerMonth',
                request_serializer=Protos_dot_flights__pb2.MonthNumber.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.FlightsPerMonth.FromString,
                )
        self.GetNumberOfFlightsInMonths = channel.unary_unary(
                '/nycflights.Flights/GetNumberOfFlightsInMonths',
                request_serializer=Protos_dot_flights__pb2.AllMonths.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.FlightsInMonths.FromString,
                )
        self.GetTop10DestinationsForOrigin = channel.unary_unary(
                '/nycflights.Flights/GetTop10DestinationsForOrigin',
                request_serializer=Protos_dot_flights__pb2.DestinationRequest.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.DestinationResponse.FromString,
                )
        self.GetAirtimeAtOrigin = channel.unary_unary(
                '/nycflights.Flights/GetAirtimeAtOrigin',
                request_serializer=Protos_dot_flights__pb2.AirtimeRequest.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.AirtimeAtOrigin.FromString,
                )
        self.GetAirtimeAtOrigins = channel.unary_unary(
                '/nycflights.Flights/GetAirtimeAtOrigins',
                request_serializer=Protos_dot_flights__pb2.AirtimeRequests.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.AirtimeAtOrigins.FromString,
                )
        self.GetDepartureArrivalDelayAtOrigin = channel.unary_unary(
                '/nycflights.Flights/GetDepartureArrivalDelayAtOrigin',
                request_serializer=Protos_dot_weather__pb2.OriginsRequest.SerializeToString,
                response_deserializer=Protos_dot_flights__pb2.DepartureArrivalAtOrigin.FromString,
                )


class FlightsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetFlights(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfFlightsPerMonth(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfFlightsInMonths(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTop10DestinationsForOrigin(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAirtimeAtOrigin(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAirtimeAtOrigins(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepartureArrivalDelayAtOrigin(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlights,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Protos_dot_flights__pb2.FlightResponse.SerializeToString,
            ),
            'GetNumberOfFlightsPerMonth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfFlightsPerMonth,
                    request_deserializer=Protos_dot_flights__pb2.MonthNumber.FromString,
                    response_serializer=Protos_dot_flights__pb2.FlightsPerMonth.SerializeToString,
            ),
            'GetNumberOfFlightsInMonths': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfFlightsInMonths,
                    request_deserializer=Protos_dot_flights__pb2.AllMonths.FromString,
                    response_serializer=Protos_dot_flights__pb2.FlightsInMonths.SerializeToString,
            ),
            'GetTop10DestinationsForOrigin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTop10DestinationsForOrigin,
                    request_deserializer=Protos_dot_flights__pb2.DestinationRequest.FromString,
                    response_serializer=Protos_dot_flights__pb2.DestinationResponse.SerializeToString,
            ),
            'GetAirtimeAtOrigin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirtimeAtOrigin,
                    request_deserializer=Protos_dot_flights__pb2.AirtimeRequest.FromString,
                    response_serializer=Protos_dot_flights__pb2.AirtimeAtOrigin.SerializeToString,
            ),
            'GetAirtimeAtOrigins': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirtimeAtOrigins,
                    request_deserializer=Protos_dot_flights__pb2.AirtimeRequests.FromString,
                    response_serializer=Protos_dot_flights__pb2.AirtimeAtOrigins.SerializeToString,
            ),
            'GetDepartureArrivalDelayAtOrigin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepartureArrivalDelayAtOrigin,
                    request_deserializer=Protos_dot_weather__pb2.OriginsRequest.FromString,
                    response_serializer=Protos_dot_flights__pb2.DepartureArrivalAtOrigin.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nycflights.Flights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Flights(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetFlights',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Protos_dot_flights__pb2.FlightResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNumberOfFlightsPerMonth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetNumberOfFlightsPerMonth',
            Protos_dot_flights__pb2.MonthNumber.SerializeToString,
            Protos_dot_flights__pb2.FlightsPerMonth.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNumberOfFlightsInMonths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetNumberOfFlightsInMonths',
            Protos_dot_flights__pb2.AllMonths.SerializeToString,
            Protos_dot_flights__pb2.FlightsInMonths.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTop10DestinationsForOrigin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetTop10DestinationsForOrigin',
            Protos_dot_flights__pb2.DestinationRequest.SerializeToString,
            Protos_dot_flights__pb2.DestinationResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAirtimeAtOrigin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetAirtimeAtOrigin',
            Protos_dot_flights__pb2.AirtimeRequest.SerializeToString,
            Protos_dot_flights__pb2.AirtimeAtOrigin.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAirtimeAtOrigins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetAirtimeAtOrigins',
            Protos_dot_flights__pb2.AirtimeRequests.SerializeToString,
            Protos_dot_flights__pb2.AirtimeAtOrigins.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDepartureArrivalDelayAtOrigin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nycflights.Flights/GetDepartureArrivalDelayAtOrigin',
            Protos_dot_weather__pb2.OriginsRequest.SerializeToString,
            Protos_dot_flights__pb2.DepartureArrivalAtOrigin.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
