# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/planes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protos/planes.proto',
  package='nycflights',
  syntax='proto3',
  serialized_options=b'\252\002\nGrpcPlanes',
  serialized_pb=b'\n\x13Protos/planes.proto\x12\nnycflights\x1a\x1bgoogle/protobuf/empty.proto\"2\n\rPlaneResponse\x12!\n\x06planes\x18\x01 \x03(\x0b\x32\x11.nycflights.Plane\"\x98\x01\n\x05Plane\x12\x0f\n\x07tailnum\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x0f\n\x07\x65ngines\x18\x06 \x01(\x05\x12\r\n\x05seats\x18\x07 \x01(\x05\x12\r\n\x05speed\x18\x08 \x01(\x05\x12\x0e\n\x06\x65ngine\x18\t \x01(\t\"H\n\x15ManufacturersResponse\x12/\n\rmanufacturers\x18\x01 \x03(\x0b\x32\x18.nycflights.Manufacturer\"4\n\x0cManufacturer\x12\x0e\n\x06planes\x18\x01 \x01(\x05\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\"\x1d\n\x0bModelNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\"p\n\x16NumberOfPlanesForModel\x12,\n\x0bmodelNumber\x18\x01 \x01(\x0b\x32\x17.nycflights.ModelNumber\x12\x12\n\nmodelCount\x18\x02 \x01(\x05\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\"d\n\x1eNumberOfPlanesForModelResponse\x12\x42\n\x16numberOfPlanesForModel\x18\x01 \x03(\x0b\x32\".nycflights.NumberOfPlanesForModel2\x9f\x02\n\x06Planes\x12>\n\tGetPlanes\x12\x16.google.protobuf.Empty\x1a\x19.nycflights.PlaneResponse\x12\x62\n%GetManufacturersWithMoreThan200Planes\x12\x16.google.protobuf.Empty\x1a!.nycflights.ManufacturersResponse\x12q\n)GetNumberOfPlanesForEachManufacturerModel\x12\x18.nycflights.Manufacturer\x1a*.nycflights.NumberOfPlanesForModelResponseB\r\xaa\x02\nGrpcPlanesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PLANERESPONSE = _descriptor.Descriptor(
  name='PlaneResponse',
  full_name='nycflights.PlaneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='planes', full_name='nycflights.PlaneResponse.planes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=114,
)


_PLANE = _descriptor.Descriptor(
  name='Plane',
  full_name='nycflights.Plane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tailnum', full_name='nycflights.Plane.tailnum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='nycflights.Plane.year', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nycflights.Plane.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='nycflights.Plane.manufacturer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='nycflights.Plane.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engines', full_name='nycflights.Plane.engines', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seats', full_name='nycflights.Plane.seats', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='nycflights.Plane.speed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine', full_name='nycflights.Plane.engine', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=269,
)


_MANUFACTURERSRESPONSE = _descriptor.Descriptor(
  name='ManufacturersResponse',
  full_name='nycflights.ManufacturersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manufacturers', full_name='nycflights.ManufacturersResponse.manufacturers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=343,
)


_MANUFACTURER = _descriptor.Descriptor(
  name='Manufacturer',
  full_name='nycflights.Manufacturer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='planes', full_name='nycflights.Manufacturer.planes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='nycflights.Manufacturer.manufacturer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=397,
)


_MODELNUMBER = _descriptor.Descriptor(
  name='ModelNumber',
  full_name='nycflights.ModelNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='nycflights.ModelNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=428,
)


_NUMBEROFPLANESFORMODEL = _descriptor.Descriptor(
  name='NumberOfPlanesForModel',
  full_name='nycflights.NumberOfPlanesForModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelNumber', full_name='nycflights.NumberOfPlanesForModel.modelNumber', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelCount', full_name='nycflights.NumberOfPlanesForModel.modelCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='nycflights.NumberOfPlanesForModel.manufacturer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=542,
)


_NUMBEROFPLANESFORMODELRESPONSE = _descriptor.Descriptor(
  name='NumberOfPlanesForModelResponse',
  full_name='nycflights.NumberOfPlanesForModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberOfPlanesForModel', full_name='nycflights.NumberOfPlanesForModelResponse.numberOfPlanesForModel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=644,
)

_PLANERESPONSE.fields_by_name['planes'].message_type = _PLANE
_MANUFACTURERSRESPONSE.fields_by_name['manufacturers'].message_type = _MANUFACTURER
_NUMBEROFPLANESFORMODEL.fields_by_name['modelNumber'].message_type = _MODELNUMBER
_NUMBEROFPLANESFORMODELRESPONSE.fields_by_name['numberOfPlanesForModel'].message_type = _NUMBEROFPLANESFORMODEL
DESCRIPTOR.message_types_by_name['PlaneResponse'] = _PLANERESPONSE
DESCRIPTOR.message_types_by_name['Plane'] = _PLANE
DESCRIPTOR.message_types_by_name['ManufacturersResponse'] = _MANUFACTURERSRESPONSE
DESCRIPTOR.message_types_by_name['Manufacturer'] = _MANUFACTURER
DESCRIPTOR.message_types_by_name['ModelNumber'] = _MODELNUMBER
DESCRIPTOR.message_types_by_name['NumberOfPlanesForModel'] = _NUMBEROFPLANESFORMODEL
DESCRIPTOR.message_types_by_name['NumberOfPlanesForModelResponse'] = _NUMBEROFPLANESFORMODELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlaneResponse = _reflection.GeneratedProtocolMessageType('PlaneResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLANERESPONSE,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.PlaneResponse)
  })
_sym_db.RegisterMessage(PlaneResponse)

Plane = _reflection.GeneratedProtocolMessageType('Plane', (_message.Message,), {
  'DESCRIPTOR' : _PLANE,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Plane)
  })
_sym_db.RegisterMessage(Plane)

ManufacturersResponse = _reflection.GeneratedProtocolMessageType('ManufacturersResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANUFACTURERSRESPONSE,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.ManufacturersResponse)
  })
_sym_db.RegisterMessage(ManufacturersResponse)

Manufacturer = _reflection.GeneratedProtocolMessageType('Manufacturer', (_message.Message,), {
  'DESCRIPTOR' : _MANUFACTURER,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Manufacturer)
  })
_sym_db.RegisterMessage(Manufacturer)

ModelNumber = _reflection.GeneratedProtocolMessageType('ModelNumber', (_message.Message,), {
  'DESCRIPTOR' : _MODELNUMBER,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.ModelNumber)
  })
_sym_db.RegisterMessage(ModelNumber)

NumberOfPlanesForModel = _reflection.GeneratedProtocolMessageType('NumberOfPlanesForModel', (_message.Message,), {
  'DESCRIPTOR' : _NUMBEROFPLANESFORMODEL,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.NumberOfPlanesForModel)
  })
_sym_db.RegisterMessage(NumberOfPlanesForModel)

NumberOfPlanesForModelResponse = _reflection.GeneratedProtocolMessageType('NumberOfPlanesForModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _NUMBEROFPLANESFORMODELRESPONSE,
  '__module__' : 'Protos.planes_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.NumberOfPlanesForModelResponse)
  })
_sym_db.RegisterMessage(NumberOfPlanesForModelResponse)


DESCRIPTOR._options = None

_PLANES = _descriptor.ServiceDescriptor(
  name='Planes',
  full_name='nycflights.Planes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=647,
  serialized_end=934,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlanes',
    full_name='nycflights.Planes.GetPlanes',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PLANERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetManufacturersWithMoreThan200Planes',
    full_name='nycflights.Planes.GetManufacturersWithMoreThan200Planes',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_MANUFACTURERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNumberOfPlanesForEachManufacturerModel',
    full_name='nycflights.Planes.GetNumberOfPlanesForEachManufacturerModel',
    index=2,
    containing_service=None,
    input_type=_MANUFACTURER,
    output_type=_NUMBEROFPLANESFORMODELRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLANES)

DESCRIPTOR.services_by_name['Planes'] = _PLANES

# @@protoc_insertion_point(module_scope)
