# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='nycflights',
  syntax='proto3',
  serialized_options=b'\252\002\013GrpcWeather',
  serialized_pb=b'\n\rweather.proto\x12\nnycflights\x1a\x1bgoogle/protobuf/empty.proto\"7\n\x0fWeatherResponse\x12$\n\x07weather\x18\x01 \x03(\x0b\x32\x13.nycflights.Weather\"\xf9\x01\n\x07Weather\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\r\n\x05month\x18\x03 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x04 \x01(\x05\x12\x0c\n\x04hour\x18\x05 \x01(\x05\x12\x0c\n\x04temp\x18\x06 \x01(\x02\x12\x0c\n\x04\x64\x65wp\x18\x07 \x01(\x02\x12\r\n\x05humid\x18\x08 \x01(\x02\x12\x10\n\x08wind_dir\x18\t \x01(\x05\x12\x12\n\nwind_speed\x18\n \x01(\x02\x12\x11\n\twind_gust\x18\x0b \x01(\x02\x12\x0e\n\x06precip\x18\x0c \x01(\x02\x12\x10\n\x08pressure\x18\r \x01(\x02\x12\r\n\x05visib\x18\x0e \x01(\x05\x12\x11\n\ttime_hour\x18\x0f \x01(\t2M\n\x08Weathers\x12\x41\n\nGetWeather\x12\x16.google.protobuf.Empty\x1a\x1b.nycflights.WeatherResponseB\x0e\xaa\x02\x0bGrpcWeatherb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='nycflights.WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weather', full_name='nycflights.WeatherResponse.weather', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=113,
)


_WEATHER = _descriptor.Descriptor(
  name='Weather',
  full_name='nycflights.Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='nycflights.Weather.origin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='nycflights.Weather.year', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='nycflights.Weather.month', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='nycflights.Weather.day', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hour', full_name='nycflights.Weather.hour', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='nycflights.Weather.temp', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dewp', full_name='nycflights.Weather.dewp', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humid', full_name='nycflights.Weather.humid', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_dir', full_name='nycflights.Weather.wind_dir', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='nycflights.Weather.wind_speed', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_gust', full_name='nycflights.Weather.wind_gust', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precip', full_name='nycflights.Weather.precip', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='nycflights.Weather.pressure', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visib', full_name='nycflights.Weather.visib', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_hour', full_name='nycflights.Weather.time_hour', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=365,
)

_WEATHERRESPONSE.fields_by_name['weather'].message_type = _WEATHER
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE
DESCRIPTOR.message_types_by_name['Weather'] = _WEATHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.WeatherResponse)
  })
_sym_db.RegisterMessage(WeatherResponse)

Weather = _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
  'DESCRIPTOR' : _WEATHER,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:nycflights.Weather)
  })
_sym_db.RegisterMessage(Weather)


DESCRIPTOR._options = None

_WEATHERS = _descriptor.ServiceDescriptor(
  name='Weathers',
  full_name='nycflights.Weathers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=367,
  serialized_end=444,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWeather',
    full_name='nycflights.Weathers.GetWeather',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_WEATHERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERS)

DESCRIPTOR.services_by_name['Weathers'] = _WEATHERS

# @@protoc_insertion_point(module_scope)
